### ISSUE TITLE
Manipulate sound

### ISSUE THREAD

**Issue by jcardenaslie** [Acedio/animalese.js#3]
Hi! 

Great work. I wonder if it is possible to tune the sound, to generate different "persons" "voices".

Thanks :)

**Comment by Acedio** [comment]
Super delayed response, but poked at this a bit today to add (very) basic pitch control. Take a look when you have a chance :) It might take a bit to show up on the demo page.

**Comment by jcardenaslie** [comment]
Hi! Thanks I just checked it out :) . Great work.
